#! /bin/bash
MASTER_ADDR=172.18.0.42 
NODE_RANK=$1
file_path=$2
NNODES=4
GPUS_PER_NODE=4


NCCL_IB_HCA=mlx5_0 \
NCCL_DEBUG=INFO \
MASTER_ADDR=$MASTER_ADDR \
MASTER_PORT=10077 \
NNODES=$NNODES \
GPUS_PER_NODE=1 \
NODE_RANK=$NODE_RANK \
CPU_TENSOR=0 \
GLOO_SOCKET_IFNAME=enp94s0np0 \
python3 broadcast_test.py
